build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  CommentOverPrivateFunction:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: false
  VariableNaming:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 160
  ReturnCount:
    active: false
  UnusedImports:
    active: false
  UnusedParameter:
    active: false
  UnusedPrivateMember:
    active: false
  WildcardImport:
    active: false
